#!/bin/sh

# Shell script to recover xmltv from http://www.kazer.org/
# Updated by Aymeric LAMBRECHT
# Original script by Stéphane DUBOIS, hosted on Github: https://github.com/clark17/tv_grab_FR_Kazer/

# Definitions of variables
TMPFILE=""
USERHASH="your_userhash_here"
DEBUG=1

# Commande stop
_stop()
{
  if [ -n $TMPFILE ]
  then
    rm "$TMPFILE"
    rm /tmp/tvguide.xml
  fi
  exit 1
}

# Commande usage
usage()
{
  echo "usage : $0 [--version|--description]"
  exit 1;
}

if [ $# -gt 1 ]
then
  usage
fi

if [ $# -eq 1 ]
then
  OPTION=$1

  if [ "--version" = "$OPTION" ] ; then
    echo "XMLTV module version 0.3"
    echo "This is tv_grab_kazer version 0.3, 2016/07/02 15:00:00"
    exit
  fi

  if [ "--description" = "$OPTION" ] ; then
    echo "France Kazer"
    exit
  fi

  if [ "--debug" = "$OPTION" ] ; then
    echo "Mode debug enabled"
    DEBUG=0
  else
    usage
    exit
  fi

fi

# Set Kazer URL with your Userhash
KAZERURL="http://www.kazer.org/tvguide.zip?u=$USERHASH"

if [ -z "$KAZERURL" ]
then
  echo "No valid KAZERURL="<url>" set" >&2
  exit 1
fi

# Name of ZIP with current shell PID
TMPFILE="/tmp/$$.xmltv.zip"

# Check if the script is stopped
trap "_stop" 1 2 3 15

# Downloading of xmltv.zip
wget -q "$KAZERURL" -O "$TMPFILE"
RETURN_WGET=$?

# We check if we have succeeded in donwloading the zipfile
if [ $RETURN_WGET -eq 0 ]
then
  # Extraction of zipfile
  unzip -q -o "$TMPFILE" -d /tmp/

  # Migrate category for TVHeadend
  sed -ri 's/<category lang="fr">Clips/<category lang="fr">Music \/ Ballet \/ Dance/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Concert/<category lang="fr">Music \/ Ballet \/ Dance/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Débat/<category lang="fr">Social \/ Political issues \/ Economics/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Dessin animé/<category lang="fr">Children'"'"'s \/ Youth programmes/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Divertissement/<category lang="fr">Show \/ Game show/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Documentaire/<category lang="fr">Education \/ Science \/ Factual topics/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Émission/<category lang="fr">Show \/ Game show/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Feuilleton/<category lang="fr">Movie \/ Drama/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Film/<category lang="fr">Movie \/ Drama/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Interview/<category lang="fr">News \/ Current affairs/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Jeu/<category lang="fr">Show \/ Game show/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Jeunesse/<category lang="fr">Children'"'"'s \/ Youth programmes/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Journal/<category lang="fr">News \/ Current affairs/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Loterie/<category lang="fr">Show \/ Game show/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Magazine/<category lang="fr">Education \/ Science \/ Factual topics/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Loterie/<category lang="fr">Show \/ Game show/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Météo/<category lang="fr">News \/ Current affairs/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Politique/<category lang="fr">Social \/ Political issues \/ Economics/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Série/<category lang="fr">Movie \/ Drama/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Spectacle/<category lang="fr">Arts \/ Culture \(without music\)/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Sport/<category lang="fr">Sports/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Talk show/<category lang="fr">Show \/ Game show/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Téléfilm/<category lang="fr">Movie \/ Drama/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Téléréalité/<category lang="fr">Show \/ Game show/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Théâtre/<category lang="fr">Arts \/ Culture \(without music\)/g' /tmp/tvguide.xml
  sed -ri 's/<category lang="fr">Variétés/<category lang="fr">Arts \/ Culture \(without music\)/g' /tmp/tvguide.xml

  # Delete temporary files
  rm "$TMPFILE"

else
  if [ $DEBUG -eq 0 ]
  then
    if [ $RETURN_WGET -eq 8 ]
    then
      echo "No changes have occurred since the last update"
    else
      echo "Unable to download the last update"
    fi
  fi
fi

# Print content of XML File
cat /tmp/tvguide.xml
