#!/bin/sh

# Shell script to recover xmltv from https://xmltv.ch/
# Author : Aymeric LAMBRECHT

# Definition of variables
OS=`uname -s`
DEBUG=1
ZIP_LINK="https://xmltv.ch/xmltv/xmltv-tnt.zip"
ZIP_PATH="/tmp/xmltv/$$.xmltv-tnt.zip"
WORKING_DIR="/tmp/xmltv/"
XMLTV_PATH="/tmp/xmltv/xmltv-tnt.xml"
SC_USER="sc-tvheadend"
SC_GROUP="sc-media"
SED_COMMAND="sed -ri"
SED_PARAMS=" \
  s|<category lang=\"fr\">autre</category>|<category lang=\"fr\">Others</category>|g;\
  s|<category lang=\"fr\">clips</category>|<category lang=\"fr\">Music / Ballet / Dance</category>|g;\
  s|<category lang=\"fr\">classique</category>|<category lang=\"fr\">Serious / Classical / Religious / Historical movie / Drama</category>|g;\
  s|<category lang=\"fr\">cérémonie</category>|<category lang=\"fr\">News / Current affairs</category>|g;\
  s|<category lang=\"fr\">cirque</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">chorégraphique</category>|<category lang=\"fr\">Music / Ballet / Dance</category>|g;\
  s|<category lang=\"fr\">concert</category>|<category lang=\"fr\">Music / Ballet / Dance</category>|g;\
  s|<category lang=\"fr\">cyclisme</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">ballet</category>|<category lang=\"fr\">Music / Ballet / Dance</category>|g;\
  s|<category lang=\"fr\">débat</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">dessin animé</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">divertissement</category>|<category lang=\"fr\">Show / Game show</category>|g;\
  s|<category lang=\"fr\">divertissement-humour</category>|<category lang=\"fr\">Show / Game show</category>|g;\
  s|<category lang=\"fr\">divers</category>|<category lang=\"fr\">Variety show</category>|g;\
  s|<category lang=\"fr\">documentaire</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">Émission</category>|<category lang=\"fr\">Show / Game show</category>|g;\
  s|<category lang=\"fr\">feuilleton</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">humour</category>|<category lang=\"fr\">Comedy</category>|g;\
  s|<category lang=\"fr\">film</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">fitness</category>|<category lang=\"fr\">Fitness and health</category>|g;\
  s|<category lang=\"fr\">fin</category>|<category lang=\"fr\">fin</category>|g;\
  s|<category lang=\"fr\">hippisme</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">interview</category>|<category lang=\"fr\">Show / Game show</category>|g;\
  s|<category lang=\"fr\">jazz</category>|<category lang=\"fr\">Jazz</category>|g;\
  s|<category lang=\"fr\">jeu</category>|<category lang=\"fr\">News / Current affairs</category>|g;\
  s|<category lang=\"fr\">jeunesse</category>|<category lang=\"fr\">Children's / Youth programmes</category>|g;\
  s|<category lang=\"fr\">journal</category>|<category lang=\"fr\">News / Current affairs</category>|g;\
  s|<category lang=\"fr\">kick-boxing</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">loterie</category>|<category lang=\"fr\">Show / Game show</category>|g;\
  s|<category lang=\"fr\">météo</category>|<category lang=\"fr\">News / Current affairs</category>|g;\
  s|<category lang=\"fr\">magazine</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">marathon</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">opéra</category>|<category lang=\"fr\">Arts / Culture (without music)</category>|g;\
  s|<category lang=\"fr\">oratorio</category>|<category lang=\"fr\">Arts / Culture (without music)</category>|g;\
  s|<category lang=\"fr\">politique</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">programme indéterminé</category>|<category lang=\"fr\">Others</category>|g;\
  s|<category lang=\"fr\">pop</category>|<category lang=\"fr\">Rock / Pop</category>|g;\
  s|<category lang=\"fr\">rap</category>|<category lang=\"fr\">Music / Ballet / Dance</category>|g;\
  s|<category lang=\"fr\">reggae</category>|<category lang=\"fr\">Folk / Traditional music</category>|g;\
  s|<category lang=\"fr\">rock</category>|<category lang=\"fr\">Rock / Pop</category>|g;\
  s|<category lang=\"fr\">série</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">spectacle</category>|<category lang=\"fr\">Arts / Culture (without music)</category>|g;\
  s|<category lang=\"fr\">sport</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">talk show</category>|<category lang=\"fr\">Show / Game show</category>|g;\
  s|<category lang=\"fr\">téléfilm</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm érotique</category>|<category lang=\"fr\">Adult movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléréalité</category>|<category lang=\"fr\">Show / Game show</category>|g;\
  s|<category lang=\"fr\">théâtre</category>|<category lang=\"fr\">Arts / Culture (without music)</category>|g;\
  s|<category lang=\"fr\">triathlon</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">variétés</category>|<category lang=\"fr\">Arts / Culture (without music)</category>|g;\
  s|<category lang=\"fr\">vtt</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">documentaire : voyage</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : histoire</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine jeunesse</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : découvertes</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine du tourisme</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : nature</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : animalier</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : environnement</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">film policier</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine de découvertes</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine d'actualité</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">série d'animation</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine culturel</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : culture</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">pop %26 rock</category>|<category lang=\"fr\">Rock / Pop</category>|g;\
  s|<category lang=\"fr\">magazine musical</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine politique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : géopolitique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : sciences et technique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : gastronomie</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine de géopolitique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine de société</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine du court métrage</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : education</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : société</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">téléfilm dramatique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : western</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">documentaire : musique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">film d'aventures</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">documentaire : politique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">film : drame</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film documentaire</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine d'information</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">film : comédie dramatique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : guerre</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">série de science-fiction</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">documentaire : santé</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : cinéma</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">téléfilm d'aventures</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">documentaire : musique classique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">film : court métrage</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine du show-biz</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine sportif</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine de l'économie</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine de reportages</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">emission politique</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">jeunesse : dessin animé</category>|<category lang=\"fr\">Children's / Youth programmes</category>|g;\
  s|<category lang=\"fr\">magazine de télé-achat</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">série dramatique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">série humoristique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm sentimental</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">série policière</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine du cinéma</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">série fantastique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine de l'automobile</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">téléfilm satirique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm humoristique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">documentaire : téléréalité</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">série judiciaire</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine culinaire</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine scientifique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">série de téléréalité</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm pour la jeunesse</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : comédie</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">sport : football</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">série d'action</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine historique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">téléfilm policier</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm de suspense</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film d'espionnage</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : thriller</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : comédie romantique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">documentaire : aventures</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">sport : multisports</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : pétanque</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : rugby</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : judo</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : rallye</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : automobilisme</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : boxe</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">multisports</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : snowboard</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : ski freestyle</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : ski</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : biathlon</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : cyclo-cross</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">biathlon</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : curling</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : skeleton</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">boxe thaï</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : volley-ball</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">documentaire : justice</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">feuilleton sentimental</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film de guerre</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm historique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm politique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">série sentimentale</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine des loisirs</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine de la décoration</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">film de science-fiction</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine de la gastronomie</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">série réaliste</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">série burlesque</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">série hospitalière</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm d'action</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">pièce de théâtre</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">série de suspense</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film d'action</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine du consommateur</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">sport : fitness</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">magazine de services</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">feuilleton réaliste</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">emission du bien-être</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">magazine de la femme</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">world music</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine littéraire</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">sports mécaniques</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">magazine hippique</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">jt sport</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">film catastrophe</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm féerique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film fantastique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : péplum</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine de l'art de vivre</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">débat parlementaire</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">documentaire : economie</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">film : autre</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : fantastique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : court métrage d'animation</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">série jeunesse</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">téléfilm de guerre</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">sport : cesta punta</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : golf</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : e-sport</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">film d'animation</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : comédie sentimentale</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">film : aventure</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">sport : voile</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">film : documentaire</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">sport : formule 1</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">e-sport</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : hockey sur glace</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">sport : patinage artistique</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">magazine religieux</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine des beaux-arts</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">sport : tennis</category>|<category lang=\"fr\">Sports</category>|g;\
  s|<category lang=\"fr\">emission religieuse</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">téléfilm d'animation</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine animalier</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">film : comédie fantastique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">jeunesse : dessin animé manga</category>|<category lang=\"fr\">Children's / Youth programmes</category>|g;\
  s|<category lang=\"fr\">magazine de charme</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine de la santé</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine du jardinage</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : civilisations</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">documentaire : beaux-arts</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">magazine éducatif</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">téléfilm fantastique</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine de l'environnement</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">emission jeunesse</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">jeunesse : dessin animé d'animation</category>|<category lang=\"fr\">Children's / Youth programmes</category>|g;\
  s|<category lang=\"fr\">jeunesse : dessin animé jeunesse</category>|<category lang=\"fr\">Children's / Youth programmes</category>|g;\
  s|<category lang=\"fr\">emission spéciale</category>|<category lang=\"fr\">Social / Political issues / Economics</category>|g;\
  s|<category lang=\"fr\">série musicale</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">magazine régional</category>|<category lang=\"fr\">Education / Science / Factual topics</category>|g;\
  s|<category lang=\"fr\">série d'aventures</category>|<category lang=\"fr\">Movie / Drama</category>|g;\
  s|<category lang=\"fr\">opéra bouffe</category>|<category lang=\"fr\">Arts / Culture (without music)</category>|g;\
  s|<category lang=\"fr\">série historique</category>|<category lang=\"fr\">Movie / Drama</category>|g; \
  s|<category>Movie</category>||g;
"

# Commande stop
_stop()
{
  if [ -d "$WORKING_DIR" ]
  then
    rm -fr "$WORKING_DIR"
  fi
  exit 1
}

# Commande usage
usage()
{
  echo "usage : $0 [--version|--description|--capabilities|--debug]"
  exit 1
}

if [ $# -gt 1 ]
then
  usage
fi

if [ $# -eq 1 ]
then
  OPTION=$1

  if [ "--version" = "$OPTION" ] ; then
    echo "XMLTV module version 1.0"
    echo "tv_grab_xmltv_fr v1.0, 2017/11/06 17:00:00"
    exit
  fi

  if [ "--description" = "$OPTION" ] ; then
    echo "XMLTV Ch"
    exit
  fi

  if [ "--capabilities" = "$OPTION" ] ; then
    echo "baseline"
    exit
  fi


  if [ "--debug" = "$OPTION" ] ; then
    echo "Mode debug enabled"
    DEBUG=0
  else
    usage
  fi

fi

if [ ! -d "$WORKING_DIR" ]
then
  #echo "Create xmltv directory"
  mkdir "$WORKING_DIR"
  chown $SC_USER:$SC_GROUP "$WORKING_DIR"
  chmod 755 "$WORKING_DIR"
fi

# Check if the script is stopped
trap "_stop" 1 2 3 15

# Downloading of xmltv.zip
wget -q "$ZIP_LINK" -O "$ZIP_PATH"
RETURN_WGET=$?

# We check if we have succeeded in donwloading the zipfile
if [ $RETURN_WGET -eq 0 ]
then
  # Extraction of zipfile
  # unzip -q -o "$ZIP_PATH" -d "$WORKING_DIR"
  7z x "$ZIP_PATH" -o"$WORKING_DIR" -y > /dev/null

  # Migrate category for TVHeadend
  # echo "SED catagories migration"
  $SED_COMMAND "$SED_PARAMS" "$XMLTV_PATH"

  # Delete temporary files
  rm "$ZIP_PATH"

else
  if [ $DEBUG -eq 0 ]
  then
    if [ $RETURN_WGET -eq 8 ]
    then
      echo "No changes have occurred since the last update"
    else
      echo "Unable to download the last update"
    fi
  fi
fi

# Print content of XML File
cat "$XMLTV_PATH"
